version: "3.9"
services:
  file-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - .:/app                    # sync code for dev (remove in prod)
      - uploads_data:/app/uploads
      - logs_data:/app/logs
      - db_data:/app/data
    restart: always
volumes:
  uploads_data:
  logs_data:
  db_data:
